config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :users, only: %i[index show] do
    resources :posts, only: %i[index show new create], as: :posts do
      resources :comments, only: %i[new create]
      resources :likes, only: %i[create]
    end
  end
  # Defines the root path route ("/")
  root to: 'users#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    can :destroy, Post if user.is? 'admin'
    can :destroy, Commnet if user.is? 'admin'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  # after_save :post_comment_counter
  belongs_to :author, class_name: 'User'
  belongs_to :post, counter_cache: true

  validates :text, presence: true, length: { maximum: 100 }

  def post_comment_counter
    post.increment!(:comments_count)
  end
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :user
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post, counter_cache: true

  def posts_likes_counter
    post.increment!(:likes_count)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments
  has_many :likes
  belongs_to :author, class_name: 'User', counter_cache: true

  validates :title, :text, presence: true, length: { minimum: 5, maximum: 30 }
  validates :text, length: { maximum: 250 }

  validates :comments_count, numericality: { only_integer: true }, comparison: { greater_than_or_equal_to: 0 }
  validates :likes_count, numericality: { only_integer: true }, comparison: { greater_than_or_equal_to: 0 }

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(params)
    if @post.save
      redirect_to root_path
    else
      render :new
    end
  end

  def author_posts_counter
    author.increment!(:posts_count)
  end

  def recent_comment
    comments.limit(5).order(created_at: :desc)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :comments, foreign_key: 'author_id'
  has_many :likes, foreign_key: 'author_id'
  has_many :posts, foreign_key: 'author_id'

  validates :name, presence: true, length: { maximum: 30 }
  validates :bio, presence: true, length: { minimum: 15 }
  validates :posts_count, numericality: { only_integer: true }, comparison: { greater_than_or_equal_to: 0 }

  def recent_post
    posts.limit(3).order(created_at: :desc)
  end

  def is?(requested_role)
    role == requested_role.to_s
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name bio])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new(text: comment_params[:text], author: current_user)
    if @comment.save
      redirect_to user_post_path(@post.author_id, @post.id)
    else
      render plain: @comment.errors.messages
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!

  def create
    @post = Post.find(params[:post_id])
    @like = @post.likes.new(post: @post, author: current_user)
    if @like.save
      redirect_to request.referrer
    else
      render plain: @like.errors.messages
    end
  end

  private

  def like_params
    params.require(:like).permit(:post_id, :user_id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!

  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts
  end

  def show
    @comment = Comment.new
    @post = Post.find(params[:id])
    @comments = @post.comments.includes(:author)
  end

  def create
    @post = current_user.posts.new(post_params)
    if @post.save
      redirect_to root_path
    else
      render plain: @post.errors.messages
    end
  end

  private

  def post_params
    params.require(:post).permit(:text, :title)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]

  def index
    @users = User.all
  end

  def show
    @post = Post.new
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cruize</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render partial: "shared/navbar" %>
    <main class="container">
    <% if notice %>
    <div class="alert alert-info"> <%= notice %> </div>
    <% end %>

    <% if alert %>
    <div class="alert alert-warning"> <%= alert %> </div>
    <% end %>
    <%= yield %>
    </main>
  </body>
</html>

app/views/posts/index.html.erb
<div class="d-flex mt-4 shadow p-3 mb-5 bg-body rounded">
    <%= image_tag(@user.photo || "https://png.pngtree.com/png-clipart/20210310/original/pngtree-boys-default-avatar-png-image_5941232.jpg", class: "w-25 h-25 me-3") %>
    <div class="d-flex flex-column mw-100 flex-fill justify-content-center">
        <h1 class="g-start-2" style="grid-row: 2"> <%= @user.name %>  </h1>
        <span class="align-self-end"> Number of Posts: <%= @user.posts_count%> </span>
    </div>
</div>
<% @posts.each_with_index do |post,index|%>
    <%= link_to user_post_path(@user, post), class:"text-decoration-none"  do %>
        <div class="mb-5 d-flex flex-column shadow p-3 mb-5 bg-body rounded">
            <span> Post # <%= index+1 %> </span>
            <h2> <%= post.title %></h2>
            <p> <%= post.text %> </p>
            <div class="align-self-end">
    <span>Comments: <%= post.comments_count %> </span> <span> Likes: <%= post.likes_count %> </span>
            </div>
        </div>
    <% end %>
    <%= form_with model: @like, url: user_post_likes_path(current_user, post.id), data: { turbo: false} do |form| %>
            <%= hidden_field_tag( value: post.id) %>  
    <%= form.submit "Like", class:"btn btn-primary"%>
    <% end %>
    <div class="d-flex flex-column p-3 mb-5 bg-body rounded">
        <% post.recent_comment.includes(:author).each do |comment|%>
            <span> <%= comment.author.name %>: <%= comment.text%> </span>
        <% end %>
    </div>
<% end %>
<nav aria-label="Page navigation example" class="mx-auto" style="width: 200px;">
  <ul class="pagination">
    <li class="page-item"><a class="page-link" href="#">Previous</a></li>
    <li class="page-item"><a class="page-link" href="#">1</a></li>
    <li class="page-item"><a class="page-link" href="#">2</a></li>
    <li class="page-item"><a class="page-link" href="#">3</a></li>
    <li class="page-item"><a class="page-link" href="#">Next</a></li>
  </ul>
</nav>

app/views/posts/show.html.erb
<div class="shadow mt-4 p-3 mb-5 bg-body rounded">
    <div class="d-flex justify-content-between">
        Post <%= @post.id %> by <%= @post.author.name %>
        <div>
            <span>Comments: <%= @post.comments_count %> </span> <span> Likes: <%= @post.likes_count %> </span>
        </div>
    </div>
    <h2> <%= @post.title %></h2>
    <p class="mt-3"> <%= @post.text%> </p>    
</div>
<%= form_with model: @like, url: user_post_likes_path(current_user, @post.id), data: { turbo: false} do |form| %>
        <%= hidden_field_tag( value: @post.id) %>  
<%= form.submit "Like", class:"btn btn-primary"%>
<% end %>
<% if @comments.exists? %>
    <div class="shadow d-flex flex-column p-3 mb-5 bg-body rounded">
        <% @comments.each do |comment|%>
            <span> <%= comment.author.name %>: <%= comment.text%> </span>
        <% end %>
    </div>
<% end %>

<div>
    <h2> Create Comment </h2>
    <%= form_with model: @comment, url: user_post_comments_path(current_user, @post.id), data: { turbo: false} do |form| %>
        <% if @post.errors.any? %>
            <div class="alert alert-danger">
                <% @post.errors.full_messages do |message| %>
                    <div> <%= message %> </div>
                <% end %>
            </div>
        <% end %>
        <div class="mb-3">
            <%= form.label :text, class: "form-label" %>
            <%= form.text_field :text, class: "form-control", id: "exampleFormControlInput1", placeholder: "Post Title" %>
        </div>
        <%= form.submit "Post Comment", class:"btn btn-primary" %>
    <% end %>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <%= link_to "Navbar", root_path, class: "navbar-brand"  %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <%
=begin%>
 <li class="nav-item">
          <%= link_to "Add post", root_path, class: "nav-link"  %>
        </li> 
<%
=end%>
      </ul>
      <ul class="navbar-nav navbar-right">
              <% if user_signed_in? %>
          <li class="nav-item">
              <%= link_to "Logout", destroy_user_session_path, data: { turbo_method: :delete }, class: "nav-link"  %>
          </li>
        <% else %>
          <li class="nav-item">
              <%= link_to "Sign Up", new_user_registration_path, class: "nav-link"  %>
          </li>
          <li class="nav-item">
              <%= link_to "Log In", new_user_session_path, class: "nav-link"  %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/users/index.html.erb
<% @users.each do |user| %>
    <%= link_to user_path(user), class:"text-decoration-none"  do %>
    <div class="d-flex p-2 shadow p-3 mb-5 bg-body rounded ">
        <%= image_tag(user.photo || "https://png.pngtree.com/png-clipart/20210310/original/pngtree-boys-default-avatar-png-image_5941232.jpg", class: "user-photo w-25 h-25 me-3", alt: "profile-imge") %>
        <div class="d-flex flex-column mw-100 flex-fill justify-content-center">
            <h1 class="g-start-2" style="grid-row: 2"> <%= user.name %>  </h1>
            <span class="align-self-end"> Number of Posts: <%= user.posts_count%> </span>
        </div>
    </div>
    <% end %>
<% end %>

app/views/users/show.html.erb
<div class="d-flex mt-4 shadow p-3 mb-5 bg-body rounded">
    <%= image_tag(@user.photo || "https://png.pngtree.com/png-clipart/20210310/original/pngtree-boys-default-avatar-png-image_5941232.jpg", class: "user-photo w-25 h-25 me-3") %>
    <div class="d-flex flex-column mw-100 flex-fill justify-content-center">
        <h1 class="g-start-2" style="grid-row: 2"> <%= @user.name %>  </h1>
        <span class="align-self-end"> Number of Posts: <%= @user.posts_count%> </span>
    </div>
</div>
<div class="mb-4 shadow p-3 mb-5 bg-body rounded">
    <h3> Bio </h3>
    <p> <%= @user.bio %> </p>
</div>

<% @user.recent_post.each_with_index do |post,index|%>
    <%= link_to user_post_path(@user, post), class:"text-decoration-none"  do %>
    <div class="mb-5 d-flex flex-column shadow p-3 mb-5 bg-body rounded">
        <span> Post # <%= index+1 %> </span>
        <h2> <%= post.title %></h2>
        <p> <%= post.text %> </p>
        <div class="align-self-end">
            <span>Comments: <%= post.comments_count %> </span> <span> Likes: <%= post.likes_count %> </span>
        </div>
    </div>
    <% end %>
    <% if user_signed_in? %>
        <%= form_with model: @like, url: user_post_likes_path(current_user, post.id), data: { turbo: false} do |form| %>
            <%= hidden_field_tag( value: @post.id) %>  
            <%= form.submit "Like", class:"btn btn-primary"%>
        <% end %>
    <% end %>
<% end %>

<% if user_signed_in? %>
<div class="mt-4 shadow p-3 mb-5 bg-body rounded">
<h2> Create Post </h2>
<%= form_with model: @post, url: user_posts_path(current_user), data: { turbo: false} do |form| %>
    <% if @post.errors.any? %>
        <div class="alert alert-danger">
            <% @post.errors.full_messages do |message| %>
                <div> <%= message %> </div>
            <% end %>
        </div>
    <% end %>
    <div class="mb-3">
        <%= form.label :title, class: "form-label" %>
        <%= form.text_field :title, class: "form-control", id: "exampleFormControlInput1", placeholder: "Post Title" %>
    </div>
    <div class="mb-3">
        <%= form.label :text, class: "form-label" %>
        <%= form.text_field :text, class: "form-control", id: "exampleFormControlInput2", placeholder: "Post Text" %>
    </div>
    <%= form.submit "Create Post", class:"btn btn-primary" %>
<% end %>
</div>
<% end %>

<%= link_to user_posts_path(@user), class: "mx-auto", style: "width: 200px; display: block" do%>
    <%= button_tag "See all posts", class: "btn btn-dark mb-4" %>
<% end %>